const mockEmails = [
    {
        id: 1,
        sender: "Dribbble",
        senderEmail: "inspiration@dribbble.com",
        subject: "Top 10 Web Designs of the Month",
        snippet: "Get inspired by the latest and greatest web designs curated just for you.",
        body: "Hello Designer,<br><br>We've curated the top 10 web designs of the month to keep your creative juices flowing. Dive in and see what the community has been up to!<br><br>Best,<br>The Dribbble Team",
        timestamp: "10:42 AM",
        category: "inbox",
        read: false,
        starred: true,
        avatar: "https://i.pravatar.cc/150?u=dribbble"
    },
    {
        id: 2,
        sender: "Alice Front-end",
        senderEmail: "alice@beemail.io",
        subject: "Re: Tailwind CSS Architecture",
        snippet: "I reviewed the PR, and I think we can optimize our utility classes further.",
        body: "Hey team,<br><br>I reviewed the recent PR regarding our Tailwind architecture. I think we can optimize our utility classes further by relying more on our theme configuration. Let's discuss this in tomorrow's standup.<br><br>Cheers,<br>Alice",
        timestamp: "09:15 AM",
        category: "inbox",
        read: true,
        starred: false,
        avatar: "https://i.pravatar.cc/150?u=alice"
    },
    {
        id: 3,
        sender: "Vercel",
        senderEmail: "deploy@vercel.com",
        subject: "Deployment Successful: beemail-prod",
        snippet: "Your project beemail-prod has been successfully deployed and is now live.",
        body: "Congratulations!<br><br>Your project <strong>beemail-prod</strong> has been successfully deployed and is now live at <em>beemail.vercel.app</em>. Check out the dashboard for more details and performance metrics.",
        timestamp: "Yesterday",
        category: "inbox",
        read: false,
        starred: false,
        avatar: "https://i.pravatar.cc/150?u=vercel"
    },
    {
        id: 4,
        sender: "Stripe",
        senderEmail: "support@stripe.com",
        subject: "Monthly Invoice Available",
        snippet: "Your monthly invoice for API usage is now ready to view.",
        body: "Hi there,<br><br>Your invoice for the period of September is now available. You can download the PDF from your billing dashboard. Let us know if you have any questions.",
        timestamp: "Yesterday",
        category: "inbox",
        read: true,
        starred: false,
        avatar: "https://i.pravatar.cc/150?u=stripe"
    },
    {
        id: 5,
        sender: "Bob Marketing",
        senderEmail: "bob@beemail.io",
        subject: "Q4 Campaign Drafts",
        snippet: "Here are the initial drafts for our Q4 marketing campaign. Let me know your thoughts.",
        body: "Team,<br><br>Attached are the initial drafts for our Q4 marketing campaign. We are leaning heavily into the 'productivity' angle. Let me know your thoughts before we proceed with the final renders.",
        timestamp: "Oct 12",
        category: "drafts",
        read: true,
        starred: true,
        avatar: "https://i.pravatar.cc/150?u=bob"
    },
    {
        id: 6,
        sender: "Me",
        senderEmail: "bilal@beemail.io",
        subject: "Project Updates",
        snippet: "I have pushed the latest changes to the main branch.",
        body: "I have pushed the latest changes to the main branch. The build is passing.",
        timestamp: "Oct 10",
        category: "sent",
        read: true,
        starred: false,
        avatar: "https://i.pravatar.cc/150?u=me"
    },
    {
        id: 7,
        sender: "Figma",
        senderEmail: "notifications@figma.com",
        subject: "Sarah commented on 'BeeMail UI'",
        snippet: "Sarah left a comment on your design file.",
        body: "Sarah commented on your frame <strong>'Mobile Inbox'</strong>:<br><br><em>\"Can we make the hover effect slightly faster here?\"</em><br><br><a href='#'>View in Figma</a>",
        timestamp: "Oct 08",
        category: "inbox",
        read: true,
        starred: true,
        avatar: "https://i.pravatar.cc/150?u=figma"
    },
    {
        id: 8,
        sender: "Sarah Designer",
        senderEmail: "sarah@beemail.io",
        subject: "Micro-animations looking great!",
        snippet: "Just wanted to say the new CSS transitions are absolutely beautiful.",
        body: "Hey!<br><br>Just wanted to say the new CSS transitions you added are absolutely beautiful. They add so much life to the app without feeling overwhelming. Great job!<br><br>Best,<br>Sarah",
        timestamp: "Oct 07",
        category: "starred",
        read: true,
        starred: true,
        avatar: "https://i.pravatar.cc/150?u=sarah"
    }
];
